version: '3.9'

services:
  emqx:
    image: emqx/emqx:5.0.8
    restart: always
    networks:
      - default
      - public
    
  telegraf:
    image: telegraf
    restart: always

  influxdb:
    image: influxdb:2.3.0-alpine
    restart: always

networks:
  default:
    name: vaidyuti

  public:
    name: vaidyuti-public
    external: true
